version: "3"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "testdb"]
      interval: 5s
      timeout: 10s
      retries: 5
  nextjs:
    build: .
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    ports:
      - "3000:3000"

volumes:
  postgres-data:
